id: I9B744C12
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T02:21:53+00:00'
last_modified: '2022-06-07T18:38:23.367952+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS16747
  title: རྗེ་བློ་བཟང་བསོད་ནམས་རྒྱ་མཚོ་དཔལ་བཟང་པོའི་རྣམ་ཐར་དད་པའི་ལྗོན་ཤིང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F096:
      image_group_id: I8LS16766
      title: ''
      total_pages: 218
      order: 1
      base_file: F096.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
